#! /bin/bash


# Run this linux-script instead of the flashread-executable if 
# resource-path-finding-problems occur.

# This script ensures that the startable program is started 
# from the place where the program (flashread) is located.
# That is appearently needed for the program to be able to find 
# resource-files that the program uses (like flashread.css)
# That problem still needs to be investigated.
# This is a workaround and can be removed when the issue is 
# solved...

# change the below path to your own flashread-location
cd /home/user/apps/flashread
./flashread

